workflows:
- workflow: CI Build
  notifications:
  - email: jitendra.ksh@gmail.com
    filter: [ failed ]

- workflow: Production Deploy
  notifications:
  - email: jitendra.ksh@gmail.com
    filter: [ requested, succeeded, failed ]
  - email: jitendra.ksh@gmail.com
    filter: [ failed ]
